import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';
import Header from '../Components/Header/Header';
import NextAuthProvider from '../providers/nextAuthProvider';
import { getServerSession } from 'next-auth';
import { authOption } from '@/src/app/api/auth/[...nextauth]/route';
import Link from 'next/link';
import Image from 'next/image';
import Container from '../Components/Container/Container';

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOption);
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          {session ? (
            <Header />
          ) : (
            <Container>
              <div className="logo_container">
                <Link href="/" className="header_logo">
                  <Image
                    src={'/logo-icon.svg'}
                    alt="header logo"
                    width={44}
                    height={17}
                  />
                  <p>PowerPulse</p>
                </Link>
              </div>
            </Container>
          )}
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
